// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.WHOISLookup
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("domainStatus")]
        public string[] DomainStatus { get; set; }

        [JsonProperty("domainName")]
        public string DomainName { get; set; }

        [JsonProperty("registryDomainID")]
        public string RegistryDomainId { get; set; }

        [JsonProperty("registrarWHOISServer")]
        public string RegistrarWhoisServer { get; set; }

        [JsonProperty("registrarURL")]
        public Uri RegistrarUrl { get; set; }

        [JsonProperty("updatedDate")]
        public DateTimeOffset UpdatedDate { get; set; }

        [JsonProperty("createdDate")]
        public DateTimeOffset CreatedDate { get; set; }

        [JsonProperty("expiryDate")]
        public DateTimeOffset ExpiryDate { get; set; }

        [JsonProperty("registrar")]
        public string Registrar { get; set; }

        [JsonProperty("registrarIANAID")]
        public long RegistrarIanaid { get; set; }

        [JsonProperty("registrarAbuseContactEmail")]
        public string RegistrarAbuseContactEmail { get; set; }

        [JsonProperty("registrarAbuseContactPhone")]
        public string RegistrarAbuseContactPhone { get; set; }

        [JsonProperty("dNSSEC")]
        public string DNssec { get; set; }
    }
}
